# =============================================================================
# Proxmox Configuration
# =============================================================================

variable "pm_api_url" {
  description = "Proxmox API URL"
  type        = string
}

variable "pm_api_token_id" {
  description = "Proxmox API Token ID"
  type        = string
  sensitive   = true
}

variable "pm_api_token_secret" {
  description = "Proxmox API Token Secret"
  type        = string
  sensitive   = true
}

variable "pm_tls_insecure" {
  description = "Allow insecure TLS connections to Proxmox API"
  type        = bool
  default     = true
}

variable "pm_node" {
  description = "Proxmox node name"
  type        = string
}

variable "pm_host" {
  description = "Proxmox host IP or hostname"
  type        = string
}

variable "proxmox_ssh_user" {
  description = "SSH user for Proxmox host"
  type        = string
  default     = "root"
}

variable "proxmox_pve_user" {
  description = "Proxmox PVE user for token creation (e.g., root@pam)"
  type        = string
  default     = "root@pam"
}

variable "proxmox_token_name" {
  description = "Name for the Proxmox API token"
  type        = string
  default     = "terraform"
}

variable "docker_ssh_user" {
  description = "SSH user for Docker LXC container"
  type        = string
  default     = "root"
}

# =============================================================================
# Docker LXC Configuration
# =============================================================================

variable "docker_hostname" {
  description = "Hostname for the Docker LXC container"
  type        = string
  default     = "docker-lxc"
}

variable "docker_ostemplate" {
  description = "OS template for Docker container"
  type        = string
  default     = "local:vztmpl/alpine-3.22-default_20250617_amd64.tar.xz"
}

variable "docker_ostemplate_name" {
  description = "Template name to download from Proxmox repository"
  type        = string
  default     = "alpine-3.22-default_20250617_amd64.tar.xz"
}

variable "docker_template_storage" {
  description = "Storage where templates are stored"
  type        = string
  default     = "local"
}

variable "docker_cores" {
  description = "Number of CPU cores"
  type        = number
  default     = 2
}

variable "docker_memory" {
  description = "Memory in MB"
  type        = number
  default     = 2048
}

variable "docker_swap" {
  description = "Swap in MB"
  type        = number
  default     = 512
}

variable "docker_rootfs_storage" {
  description = "Storage for rootfs"
  type        = string
  default     = "local-zfs"
}

variable "docker_rootfs_size" {
  description = "Rootfs size"
  type        = string
  default     = "16G"
}

variable "docker_network_bridge" {
  description = "Network bridge"
  type        = string
  default     = "vmbr0"
}

variable "docker_network_ip" {
  description = "IP address (dhcp or CIDR)"
  type        = string
  default     = "dhcp"
}

variable "docker_install_compose" {
  description = "Install Docker Compose"
  type        = bool
  default     = true
}

variable "docker_start_on_boot" {
  description = "Start on boot"
  type        = bool
  default     = true
}

# =============================================================================
# Infisical Configuration
# =============================================================================

variable "enable_infisical" {
  description = "Enable Infisical module"
  type        = bool
  default     = false
}

variable "infisical_port" {
  description = "Infisical HTTP port"
  type        = number
  default     = 8080
}

variable "infisical_project_name" {
  description = "Infisical project name"
  type        = string
  default     = "selfhost"
}

# Bootstrap outputs (from infisical_bootstrap.auto.tfvars)
variable "infisical_admin_token" {
  description = "Infisical admin token (generated by bootstrap)"
  type        = string
  default     = ""
  sensitive   = true
}

variable "infisical_org_id" {
  description = "Infisical organization ID (generated by bootstrap)"
  type        = string
  default     = ""
}

# Machine Identity credentials (from infisical_token.auto.tfvars)
variable "infisical_client_id" {
  description = "Infisical Machine Identity Client ID"
  type        = string
  default     = ""
  sensitive   = true
}

variable "infisical_client_secret" {
  description = "Infisical Machine Identity Client Secret"
  type        = string
  default     = ""
  sensitive   = true
}
