variable "docker_hostname" {
  description = "Hostname for the Docker LXC container"
  type        = string
  default     = "docker-lxc"
}

variable "docker_ostemplate" {
  description = "OS template for Docker container"
  type        = string
  default     = "local:vztmpl/alpine-3.22-default_20250617_amd64.tar.xz"
}

variable "docker_ostemplate_name" {
  description = "Template name to download from Proxmox repository"
  type        = string
  default     = "alpine-3.22-default_20250617_amd64.tar.xz"
}

variable "docker_template_storage" {
  description = "Storage where templates are stored"
  type        = string
  default     = "local"
}

variable "docker_password" {
  description = "Root password for Docker container (minimum 5 characters)"
  type        = string
  sensitive   = true
}

variable "docker_cores" {
  description = "Number of CPU cores for Docker container"
  type        = number
  default     = 2
}

variable "docker_memory" {
  description = "Memory in MB for Docker container"
  type        = number
  default     = 2048
}

variable "docker_swap" {
  description = "Swap memory in MB for Docker container"
  type        = number
  default     = 512
}

variable "docker_rootfs_storage" {
  description = "Storage for Docker container rootfs"
  type        = string
  default     = "local-zfs"
}

variable "docker_rootfs_size" {
  description = "Rootfs size for Docker container (e.g., 16G)"
  type        = string
  default     = "16G"
}

variable "docker_network_bridge" {
  description = "Network bridge for Docker container"
  type        = string
  default     = "vmbr0"
}

variable "docker_network_ip" {
  description = "IP address configuration for Docker container (DHCP or CIDR)"
  type        = string
  default     = "dhcp"
}

variable "docker_install_compose" {
  description = "Install Docker Compose"
  type        = bool
  default     = true
}

variable "docker_start_on_boot" {
  description = "Start Docker container on boot"
  type        = bool
  default     = true
}

variable "docker_host_ip" {
  description = "IP address of the Docker LXC container for SSH connection"
  type        = string
}

variable "infisical_admin_email" {
  description = "Email for Infisical admin user"
  type        = string
}

variable "infisical_client_id" {
  description = "Infisical Machine Identity Client ID (generated by bootstrap)"
  type        = string
  default     = ""
  sensitive   = true
}

variable "infisical_client_secret" {
  description = "Infisical Machine Identity Client Secret (generated by bootstrap)"
  type        = string
  default     = ""
  sensitive   = true
}

# Bootstrap outputs (auto-generated by bootstrap_infisical.py)
variable "infisical_admin_token" {
  description = "Infisical admin token (generated by bootstrap script)"
  type        = string
  default     = ""
  sensitive   = true
}

variable "infisical_org_id" {
  description = "Infisical organization ID (generated by bootstrap script)"
  type        = string
  default     = ""
}

# Legacy token variable (kept for backward compatibility)
variable "infisical_token" {
  description = "Infisical API token (deprecated, use infisical_admin_token)"
  type        = string
  default     = ""
  sensitive   = true
}

variable "infisical_org_name" {
  description = "Infisical organization name"
  type        = string
  default     = "Selfhost"
}

variable "infisical_project_name" {
  description = "Infisical project name"
  type        = string
  default     = "selfhost"
}

variable "infisical_port" {
  description = "Infisical HTTP port"
  type        = number
  default     = 8080
}

variable "enable_infisical" {
  description = "Enable Infisical module (set to true after docker_lxc is deployed with SSH)"
  type        = bool
  default     = false
}

