# Module enable/disable
variable "enabled" {
  description = "Enable/disable all resources in this module"
  type        = bool
  default     = true
}

# Server configuration
variable "server_url" {
  description = "Infisical server URL (for CORS and redirects)"
  type        = string
}

variable "infisical_port" {
  description = "Infisical HTTP port"
  type        = number
  default     = 8080
}

# Admin configuration
variable "admin_email" {
  description = "Email for Infisical admin user"
  type        = string
}

variable "org_name" {
  description = "Infisical organization name"
  type        = string
  default     = "Selfhost"
}

variable "project_name" {
  description = "Infisical project name"
  type        = string
  default     = "selfhost"
}

# Bootstrap outputs (from infisical_bootstrap.auto.tfvars)
variable "admin_token" {
  description = "Infisical admin token (generated by bootstrap)"
  type        = string
  default     = ""
  sensitive   = true
}

variable "org_id" {
  description = "Infisical organization ID (generated by bootstrap)"
  type        = string
  default     = ""
}

# Machine Identity credentials (from infisical_token.auto.tfvars)
variable "client_id" {
  description = "Infisical Machine Identity Client ID"
  type        = string
  default     = ""
  sensitive   = true
}

variable "client_secret" {
  description = "Infisical Machine Identity Client Secret"
  type        = string
  default     = ""
  sensitive   = true
}

# Docker configuration
variable "network_name" {
  description = "Docker network name for Infisical stack"
  type        = string
  default     = "infisical"
}

variable "network_subnet" {
  description = "Docker network subnet CIDR"
  type        = string
  default     = "172.20.0.0/16"
}

variable "postgres_data_volume" {
  description = "PostgreSQL data volume name"
  type        = string
  default     = "infisical_postgres_data"
}

variable "redis_data_volume" {
  description = "Redis data volume name"
  type        = string
  default     = "infisical_redis_data"
}

variable "postgres_image" {
  description = "PostgreSQL Docker image"
  type        = string
  default     = "postgres:15-alpine"
}

variable "redis_image" {
  description = "Redis Docker image"
  type        = string
  default     = "redis:7-alpine"
}

variable "infisical_image" {
  description = "Infisical Docker image"
  type        = string
  default     = "infisical/infisical:latest"
}

variable "postgres_user" {
  description = "PostgreSQL username"
  type        = string
  default     = "postgres"
}

variable "postgres_db" {
  description = "PostgreSQL database name"
  type        = string
  default     = "infisical"
}

# Proxmox Token Management
variable "proxmox_host" {
  description = "Proxmox host IP or hostname for SSH token creation"
  type        = string
  default     = ""
}

variable "proxmox_ssh_user" {
  description = "SSH user for Proxmox host"
  type        = string
  default     = "root"
}

variable "proxmox_pve_user" {
  description = "Proxmox PVE user for token creation (e.g., root@pam)"
  type        = string
  default     = "root@pam"
}

variable "proxmox_token_name" {
  description = "Name for the Proxmox API token"
  type        = string
  default     = "terraform"
}
