#!/usr/bin/env python3
"""
Minimal Infisical bootstrap script.
Only performs initial admin/org setup that has no Terraform resource equivalent.
After bootstrap, Terraform takes over using infisical_identity resources.

Usage:
    python bootstrap_infisical.py <url> <email> <password> <org_name>

Outputs:
    Creates infisical_bootstrap.auto.tfvars with admin token for Terraform to use.
"""

import sys
import time
from pathlib import Path

import requests
from requests.exceptions import RequestException


def log_info(msg: str) -> None:
    print(f"[INFO] {msg}")


def log_error(msg: str) -> None:
    print(f"[ERROR] {msg}")


def wait_for_api(base_url: str, max_retries: int = 60) -> bool:
    """Wait for Infisical API to be ready."""
    log_info(f"Waiting for Infisical API at {base_url}...")

    for i in range(max_retries):
        try:
            resp = requests.get(f"{base_url}/api/status", timeout=5)
            if resp.status_code == 200:
                log_info("Infisical API is ready!")
                return True
        except RequestException:
            pass

        if i > 0 and i % 10 == 0:
            log_info(f"Still waiting... ({i}/{max_retries})")
        time.sleep(2)

    log_error("Infisical API not ready after timeout")
    return False


def bootstrap(base_url: str, email: str, password: str, org_name: str) -> dict | None:
    """Bootstrap Infisical with admin user and organization."""
    log_info("Attempting Infisical bootstrap...")

    try:
        resp = requests.post(
            f"{base_url}/api/v1/admin/bootstrap",
            json={
                "email": email,
                "password": password,
                "organization": org_name
            },
            timeout=30
        )

        if resp.status_code == 200:
            data = resp.json()
            log_info("Bootstrap successful!")
            return {
                "token": data["identity"]["credentials"]["token"],
                "org_id": data["organization"]["id"]
            }

        if resp.status_code == 400 and "already" in resp.text.lower():
            log_info("Instance already bootstrapped")
            return None

        log_error(f"Bootstrap failed: {resp.status_code} - {resp.text}")
        return None

    except RequestException as e:
        log_error(f"Bootstrap request failed: {e}")
        return None


def main():
    if len(sys.argv) < 5:
        print(__doc__)
        sys.exit(1)

    url = sys.argv[1]
    email = sys.argv[2]
    password = sys.argv[3]
    org_name = sys.argv[4]

    output_file = Path("infisical_bootstrap.auto.tfvars")

    # Check if already bootstrapped
    if output_file.exists():
        with open(output_file, 'r', encoding='utf-8') as f:
            if "infisical_admin_token" in f.read():
                log_info("Bootstrap already completed (token file exists)")
                sys.exit(0)

    # Wait for API
    if not wait_for_api(url):
        sys.exit(1)

    # Bootstrap
    result = bootstrap(url, email, password, org_name)

    if result:
        log_info(f"Saving admin token to {output_file}...")
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(f'# Generated by bootstrap_infisical.py - DO NOT EDIT\n')
            f.write(f'infisical_admin_token = "{result["token"]}"\n')
            f.write(f'infisical_org_id      = "{result["org_id"]}"\n')
        log_info("Done! Run 'terraform apply' to create Machine Identity.")
    elif output_file.exists():
        log_info("Using existing bootstrap token")
    else:
        log_error("Bootstrap failed and no existing token found")
        log_error("Manual intervention required or destroy and recreate Infisical")
        sys.exit(1)


if __name__ == "__main__":
    main()

